namespace: marketplace

replicaCount: 1

image:
  repository: ghcr.io/thclab/oca-repository
  tag: "2.0.0-rc.1"
  pullPolicy: Always
  pullSecret: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  hostBase: nextgen.hiro-develop.nl
  tlsSecret: oca-repository-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

persistence:
  enabled: false
  existingClaim: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: ""

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: DS_GLOBAL_OCA_REPOSITORY_BUNDLES_URL
    value: "https://oca-repository.marketplace.nextgen.hiro-develop.nl/oca-bundles"


nodeSelector:
  role: marketplace

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

tolerations: []

affinity: {}

config:
  data: |
    application:
      host: 0.0.0.0
      port: 8000
      data_entries_path: "/tmp"
      log_to_file: true
      # if log_to_file set to true and path not set default: /var/log/oca_repository.log
      log_path: "./logs/oca_repository.log"
      # path to directory where overlayfile definitions are located
      overlayfile_dir: "./core_overlays"

    database:
      path: "./db"

    cache_storage:
      path: "./cache"

    search_engine:
      path: "./db_search"

    ocafiles_cache:
      path: "./oca_repo_cache"

