namespace: ki

replicaCount: 1

image:
  repository: ghcr.io/thclab/oca-repository
  tag: "0.8.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  hostBase: nextgen.hiro-develop.nl
  tlsSecret: oca-repository-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

persistence:
  enabled: false
  existingClaim: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: ""
