namespace: marketplace

replicaCount: 1

image:
  repository: ghcr.io/thclab/oca-repository
  tag: "2.0.0-rc.1"
  pullPolicy: Always
  pullSecret: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  hostBase: nextgen.hiro-develop.nl
  tlsSecret: oca-repository-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

persistence:
  enabled: false
  existingClaim: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: ""

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: DS_GLOBAL_OCA_REPOSITORY_BUNDLES_URL
    value: "https://oca-repository.marketplace.nextgen.hiro-develop.nl/api/v2/oca-bundles"


nodeSelector:
  role: marketplace

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

tolerations: []

affinity: {}

config:
  data: |
    application:
      host: 0.0.0.0
      port: 8000
      log_to_file: false
      overlayfile_dir: "/data/overlays"
      data_entries_path: "/data/entries"
    database:
      path: "/data/db"
    cache_storage:
      path: "/data/cache"
    search_engine:
      path: "/data/db_search"
    ocafiles_cache:
      path: "/data/oca_repo_cache"

