name: Build and publish OCA Repository Helm Chart

on:
  push:
    branches:
      - main
    tags:
      - '**'
  workflow_dispatch:

jobs:
  publish_helm:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Set chart version
        run: |
          VERSION_APP=$(cat VERSION)
          echo "VERSION_APP=$VERSION_APP" >> $GITHUB_ENV

      - name: Package Helm chart
        run: |
          cd server/charts
          helm dependency update oca-repository || true
          helm package oca-repository --version $VERSION_APP --app-version $VERSION_APP
          mkdir -p ../../helm-charts
          mv oca-repository-$VERSION_APP.tgz ../../helm-charts/

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: ./helm-charts
          target_dir: ./helm-charts
