name: Build and publish OCA Repository Helm Chart

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'releases/**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Make versions
        id: versions
        run: |
          # Static app version from values.yaml (e.g., image.tag: "0.8.1")
          APP_VERSION=$(yq '.image.tag' server/charts/oca-repository/values.yaml | tr -d '"')

          # Dynamic chart version (semver compatible with dashes)
          DAY_OF_MONTH=$(date +%-d)
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9-]/-/g')
          COMMIT_SHA=$(git rev-parse --short HEAD)
          CHART_VERSION="0.1.0-dev-${DAY_OF_MONTH}-${BRANCH_NAME}-${COMMIT_SHA}"

          echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT
          echo "chart_version=${CHART_VERSION}" >> $GITHUB_OUTPUT

      - name: Package Helm chart
        run: |
          cd server/charts
          helm dependency update oca-repository || true
          helm lint oca-repository
          helm package oca-repository \
            --version ${{ steps.versions.outputs.chart_version }} \
            --app-version ${{ steps.versions.outputs.app_version }}
          mkdir -p ../../helm-charts
          mv oca-repository-${{ steps.versions.outputs.chart_version }}.tgz ../../helm-charts/

      - name: Create a GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        run: gh release create "${{ steps.versions.outputs.chart_version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: "./server/charts"
          target_dir:  "./helm-charts/"
