name: Build and publish OCA Repository Helm Chart

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'releases/**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: hiro-microdatacenters-bv/ds-oca-integration

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Make versions
        run: |
          cd "${{ github.workspace }}"
          chmod +x ./tools/version.sh
          ./tools/version.sh "${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}"
          echo "VERSION_APP=$(cat ./VERSION_APP)" >> $GITHUB_ENV
          echo "DOCKER_IMAGES=$(cat ./DOCKER_IMAGES)" >> $GITHUB_ENV
          echo "DOCKER_TAGS=$(cat ./VERSION_DOCKER)" >> $GITHUB_ENV
          echo "CHART_VERSION=$(cat ./VERSION_CHART)" >> $GITHUB_ENV

      - name: Package Helm chart
        run: |
          cd server/charts
          helm dependency update oca-repository || true
          helm lint oca-repository
          helm package oca-repository \
            --version $CHART_VERSION \
            --app-version $VERSION_APP
          mkdir -p ../../helm-charts
          mv oca-repository-$CHART_VERSION.tgz ../../helm-charts/
      - name: Create a GitHub Release
        run: gh release create "${{ env.VERSION_APP }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: "./server/charts"
          target_dir:  "./helm-charts/"
